stages:
  - test

run-api-tests:
  stage: test
  image: node:20
  script:
    - npm install -g newman
    - newman run postman/Football-API.postman_collection.json
        -e postman/production.postman_environment.json
        --reporters cli
  only:
    - main
    - merge_requests