stages:
  - test
  - lint

run-lint:
  stagge: lint
  image: node:20
  script:
    - npm install
    - npm run lint

run-api-tests:
  stage: test
  image: node:20
  script:
    - npm install -g newman
    - npm test